#!/bin/bash
echo -e "\nscreenfetch()\n{\n\t./WinScreenFetch\n\treturn\n}" >> ~/.bashrc
echo "Successfully installed!"
echo "This program will only work if the screenfetch script is in the home directory"
